name: Release
on:
  release:
    types:
    - published
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install build wheel
    - name: Build package
      run: python -m build --sdist --wheel --outdir=dist
    - name: Deploy package
      if: '!github.event.repository.fork'
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
        packages_dir: dist
